### ISSUE TITLE
Conda installation doesn't work on macOS with python3.9.10

### ISSUE THREAD

**Issue by tddschn** [easy-graph/Easy-Graph#42]
OS: macOS Monterey 12.3
CPU: Intel

```
$ which python3
/usr/local/Caskroom/miniconda/base/envs/lab/bin/python3

$ python3 --version
Python 3.9.10

$ conda install -c fudanmsn Python-EasyGraph
...
# installed easygraph from
# + python-easygraph              0.2a35  py39_0                  fudanmsn/osx-64           3MB
...

$ python3 -c 'import easygraph'
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/easygraph/__init__.py", line 8, in <module>
    import easygraph.functions
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/easygraph/functions/__init__.py", line 5, in <module>
    from easygraph.functions.drawing import *
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/easygraph/functions/drawing/__init__.py", line 3, in <module>
    from .plot import *
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/easygraph/functions/drawing/plot.py", line 4, in <module>
    import statsmodels.api as sm
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/statsmodels/api.py", line 105, in <module>
    from .graphics import api as graphics
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/statsmodels/graphics/api.py", line 1, in <module>
    from . import tsaplots as tsa
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/statsmodels/graphics/tsaplots.py", line 11, in <module>
    from statsmodels.tsa.stattools import acf, pacf
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/statsmodels/tsa/stattools.py", line 19, in <module>
    from scipy.signal import correlate
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/scipy/signal/__init__.py", line 329, in <module>
    from ._spectral_py import *
  File "/usr/local/Caskroom/miniconda/base/envs/lab/lib/python3.9/site-packages/scipy/signal/_spectral_py.py", line 8, in <module>
    from ._spectral import _lombscargle
KeyboardInterrupt
```

**Comment by tddschn** [comment]
`python3 -c 'import easygraph'` took too long and I had to kill it. Pip installation works just fine.

**Comment by coreturn** [comment]
Thanks for the feedback, I'll take a look at the issue.
